language: php

php:
  - 5.6
  - 5.5
  - 5.4
  - 5.3
  - hhvm
  - hhvm-nightly

before_script:
  - wget http://getcomposer.org/composer.phar
  - php composer.phar install

script: phpunit -c phpunit.xml.travis

matrix:
  allow_failures:
      - php: hhvm
      - php: hhvm-nightly